languageCode = "en-us"
title = "Stefan Haider"
baseurl = "https://www.haider.io"
theme = "beautifulhugo"
disqusShortname = "www-haider-io"
googleAnalytics = "UA-92611645-1"
buildDrafts = false
buildFuture = true

[Params]
  subtitle = "Software Engineer"
  logo = "img/portrait.png"
  favicon = "img/favicon.png"
  commit = false
  description = "Stefan Haider's site and blog"

[Author]
  name = "Stefan Haider"
  email = "stefan@haider.io"
  facebook = "haidelber"
  github = "haidelber"
  linkedin = "sthaider"
  xing = "Stefan_Haider10"
#  stackoverflow = "users/4759472/haidelber"
#  instagram = "username"
#  youtube = "user/geohaidelber" # or channel/channelname

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 100

[[menu.main]]
    name = "Résumé"
    url = "/page/resume/"
    weight = 200

[[menu.main]]
    name = "Projects"
    url = "/page/projects/"
    weight = 300

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 400